# Configuração do MongoDB
quarkus.mongodb.connection-string=mongodb+srv://joak:joak@cluster0.d7ufm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
quarkus.mongodb.database=casino_db

# Habilitar CORS para qualquer origem
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=accept,authorization,content-type
