# Usa uma imagem do Quarkus otimizada para produção
FROM quay.io/quarkus/quarkus-micro-image:2.0

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do build do Quarkus para o container
COPY target/quarkus-app/ /app/

# Comando para rodar a aplicação
CMD ["java", "-jar", "/app/quarkus-run.jar"]
